name = "Artisan"
license = "MIT"
licenselink = "https://github.com/EricHripko/artisan/blob/master/LICENSE.txt"
description = "Hugo theme for programmer blogs."
homepage = "https://eric.hripko.com/"
tags = []
features = []
min_version = "0.41"

[author]
name = "Eric Hripko"
homepage = "https://eric.hripko.com"
